version: '3'
services:
    sgp-es2-db:
        image: mysql:latest
        container_name: sgp-es2-db
        env_file: ./.env.production
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
        ports:
            - '3306:3306'
        volumes:
            - database-volume:/var/lib/mysql
    sgp-es2-api:
        container_name: sgp-es2-api
        depends_on:
            - sgp-es2-db
        build: ./
        restart: unless-stopped
        env_file: ./.env.production
        ports:
            - 3000:3000
        stdin_open: true
        tty: true
        volumes:
            - ./:/app
            - /app/node_modules
            - ./firebase.credentials.json:/app/../firebase.credentials.json
        networks:
            - default
volumes:
    database-volume:
