version: '3.8'
services:
    db:
        container_name: db
        image: mysql:latest
        env_file: .env.production
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
        ports:
            - 3306:3306
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - database-volume:/var/lib/mysql
    sgp-es2-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nest-api
        restart: always
        ports:
            - 3000:3000
        depends_on:
            db:
                condition: service_started
        env_file:
            - .env.production
        volumes:
            - ./:/app
            - /app/node_modules
            - ./firebase.credentials.json:/app/../firebase.credentials.json
            - ./package.json:/app/../package.json
        links:
            - db
volumes:
    database-volume:
